version: '3.7'
services:
  db:
    image: 'postgres'
    container_name: db
    ports:
      - '5431:5432'
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: potgres
    volumes:
      - data:/var/lib/postgresql/data
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    container_name: Kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  producer_service:
    build: ./producer-service
    container_name: producer-service
    command: sh -c "dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9092 npm start"
    ports:
      - '4000:4000'
    depends_on:
      - zookeeper
      - kafka
  consumer_service:
    build: ./consumer-service
    container_name: consumer-service
    command: sh -c "dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9092 -wait tcp://db:5432 npm start"
    ports:
      - '4002:4002'
    depends_on:
      - db
      - zookeeper
      - kafka
  query_service:
    build: ./query-service
    container_name: query-service
    command: sh -c "dockerize -wait tcp://db:5432 npm start"
    ports:
      - '4001:4001'
    depends_on:
      - db

volumes:
  data: